version: 2
image: ubuntu:16.04
jobs:
  build:
    docker:
      - image: node:9.7.0

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - dependencies-{{ checksum "yarn.lock" }}
          - dependencies-

      - run: yarn

      - run: |
          cd packages/cockpit
          yarn lint
          yarn test
          yarn build

      - run: |
          cd packages/pilot
          yarn build

      - save_cache:
          paths:
            - node_modules
            - packages/cockpit/node_modules
            - packages/pilot/node_modules
          key: dependencies-{{ checksum "yarn.lock" }}
