version: 2
image: ubuntu:16.04
jobs:
  build:
    docker:
      - image: node:9

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - dependencies-{{ checksum "yarn.lock" }}
          - dependencies-

      - run: yarn

      - run: |
          cd packages/cockpit
          yarn lint
          yarn test
          yarn build

      - run: |
          cd packages/pilot
          yarn build

      - save_cache:
          paths:
            - node_modules
            - packages/cockpit/node_modules
            - packages/pilot/node_modules
          key: dependencies-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: packages
          paths:
            - pilot
  deploy_stg:
    machine:
        enabled: true
    working_directory: ~/repo

    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Deploy to S3 files of version for stg
          command: |
            mkdir latest
            cp -rf pilot/ latest
            mkdir -p versions/${CIRCLE_TAG}
            cp -rf pilot/ versions/${CIRCLE_TAG}
            rm -rf pilot
            aws s3 sync . s3://beta.dashboard.stg.pagarme.net
  # deploy_prd:
  #   machine:
  #       enabled: true
  #   working_directory: ~/repo

  #   steps:
  #     - attach_workspace:
  #         at: ~/repo
  #     - run:
  #         name: Deploy to S3 files of version fo prod
  #         command: |
  #           mkdir latest
  #           cp index.js latest
  #           mkdir -p versions/${CIRCLE_TAG}
  #           mv index.js versions/${CIRCLE_TAG}
  #           AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_PRD AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_PRD aws s3 sync . s3://checkout.prd.pagarme.net
workflows:
  version: 2
  build-and-deploy:
    jobs:
    - build:
        filters:
          tags:
            only: /^v.*/
    - deploy_stg:
        requires:
        - build
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v([0-9]+).([0-9]+).([0-9]+).*$/
    # - hold:
    #     type: approval
    #     requires:
    #       - deploy_stg
    #     filters:
    #       branches:
    #         ignore: /.*/
    #       tags:
    #         only: /^v([0-9]+).([0-9]+).([0-9]+)$/
    # - deploy_prd:
    #     requires:
    #     - hold
    #     filters:
    #       branches:
    #         ignore: /.*/
    #       tags:
    #         only: /^v([0-9]+).([0-9]+).([0-9]+)$/
